//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Icons
    {
        public const string BundleName = "icons";
        public const string BLACKHOLEICON = "BlackHoleIcon";
        public const string BOMBICON = "BombIcon";
        public const string COINDROPICON = "CoinDropIcon";
        public const string COINENOUGHICON = "CoinEnoughIcon";
        public const string EXPDROPICON = "ExpDropIcon";
        public const string FIREBALLICON = "FireballIcon";
        public const string FIRSTMEETICON = "FirstMeetIcon";
        public const string HPBOTTLEDROPICON = "HPBottleDropIcon";
        public const string KNIFEICON = "KnifeIcon";
        public const string LEVELUPENOUGHICON = "LevelUpEnoughIcon";
        public const string LIGHTNINGFIELDICON = "LightningFieldIcon";
        public const string MAGNETICON = "MagnetIcon";
        public const string MAXHPBOOSTICON = "MaxHPBoostIcon";
        public const string PICKRANGEICON = "PickRangeIcon";
        public const string SPEEDICON = "SpeedIcon";
        public const string STRIKERATEICON = "StrikeRateIcon";
        public const string TIMEENOUGHICON = "TimeEnoughIcon";
    }
    public class Sfx
    {
        public const string BundleName = "sfx";
        public const string ABILITYLEVELUP = "AbilityLevelUp";
        public const string BOMB = "Bomb";
        public const string COIN = "Coin";
        public const string DIE = "Die";
        public const string ENEMY_DIE = "Enemy_die";
        public const string EXP = "Exp";
        public const string GAMEPASS = "GamePass";
        public const string GETALLEXP = "GetAllExp";
        public const string HIT = "Hit";
        public const string HP = "Hp";
    }
    public class Uibeginpanel_prefab
    {
        public const string BundleName = "uibeginpanel_prefab";
        public const string UIBEGINPANEL = "UIBeginPanel";
    }
    public class Uiendpanel_prefab
    {
        public const string BundleName = "uiendpanel_prefab";
        public const string UIENDPANEL = "UIEndPanel";
    }
    public class Uigamepanel_prefab
    {
        public const string BundleName = "uigamepanel_prefab";
        public const string UIGAMEPANEL = "UIGamePanel";
    }
    public class Uirewardpanel_prefab
    {
        public const string BundleName = "uirewardpanel_prefab";
        public const string UIREWARDPANEL = "UIRewardPanel";
    }
    public class Uiwinpanel_prefab
    {
        public const string BundleName = "uiwinpanel_prefab";
        public const string UIWINPANEL = "UIWinPanel";
    }
}
